### Invocar al Servidor en mi maquina: LocalHost
### Inviar lista en generar
GET http://localhost:8080/api/v1/tipodeproducto  
Content-Type: application/json
### Puede Ver  el contenido de  unico por id
GET http://localhost:8080/api/v1/tipodeproducto/0ebc65f8-0582-4dec-9c19-be46a93d743c
Content-Type: application/json

### Crea 
POST  http://localhost:8080/api/v1/tipodeproducto 
Content-Type: application/json

{
    "kindOfProduct": "lapiz caligrafico"
}

### Editar 
PUT  http://localhost:8080/api/v1/tipodeproducto/b4a5d789-7957-4ea6-afe4-dd13d37375f4
Content-Type: application/json

{
    "kindOfProduct": "Boligrafo"
}

###Eliminar
DELETE  http://localhost:8080/api/v1/tipodeproducto/6003f50f-d711-4436-8ea5-8ef6c7aa33d2 
Content-Type: application/json