### Invocar al Servidor en mi maquina: LocalHost
### Inviar lista en generar
GET http://localhost:8080/api/v1/user
Content-Type: application/json

### Crea 
POST  http://localhost:8080/api/v1/user
Content-Type: application/json

{
  "idUser": "c4560c3d-fcf6-4c40-a04f-17c2b8c87d59",
  "persona": {
    "id": "6826009d-f321-4468-8404-9b062e40a8a0"
  },
  "roles": [
    {
      "idRoles": "463a8850-d5ad-4cc4-ae49-c834a68d1f87"
    }
  ],
  "loginUser": "john.doe",
  "passwordUser": "password123",
  "email": "john.doe@example.com"
}
###Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "loginUser": "john.doe",
  "passwordUser": "password123"
}
###Login
GET http://localhost:8080/api/v1/user
Content-Type: application/json